### ISSUE TITLE
foundation not found or unreadable

### ISSUE THREAD

**Issue by FossPrime** [bezoerb/generator-grunt-symfony#12]
After a vanilla install with Foundation I received this message

```
Running "sass:all" (sass) task
>> file to import not found or unreadable: foundation/scss/foundation
>> Current dir: /home/amama/git/cookie-db/app/Resources/public/styles/
>>   Line 1  Column 9  app/Resources/public/styles/main.scss
```

My guess is I need to reinstall foundation sass... through gem, npm, bower or that other jspm, any pointers?

UPDATE
same thing happens with bootstrap.

```
Running "sass:all" (sass) task
>> file to import not found or unreadable: bootstrap-sass-official/assets/stylesheets/_bootstrap
>> Current dir: /home/amama/git/cookie-db/app/Resources/public/styles/
>>   Line 1  Column 10  app/Resources/public/styles/main.scss
Warning:  Use --force to continue.
```

**Comment by bezoerb** [comment]
@Reyncor looks like you got it fixed? What was the problem?

**Comment by FossPrime** [comment]
It was probably due to an outdated node. Though it sounds like I didn't do jspm install, I had never used SystemJS before, this is a fantasticly complex framwork that requires quite a bit of set up I've made some instructions for my self:

Toolset
The project is built with the yo generator grunt-symfony which most notably requires up to date
Ruby / Gems / Compass
Node / Node packages
Php / Php intl
composer
Keep ALL of your packages up to date!

Installing dev environment
npm install
bower install
jspm install
composer install
