### ISSUE TITLE
Feature Request: Handlebars template engine instead of Twig

### ISSUE THREAD

**Issue by FossPrime** [bezoerb/generator-grunt-symfony#13]
Handlebars is awesome and has become the standard. It would be nice to simply copy the handlebars templates from completely unrelated projects using different technologies. This would of course, be an option.

Might work on this in the future.

**Comment by brunowego** [comment]
+1

**Comment by FossPrime** [comment]
I'd love it... but it is without a doubt, out of the scope of this project. It should be a separate Symfony bundle, and then we would give ourselves the option to install it. It's not a small task as every bundle assumes twig... Doctrine, Forms and third party ones. I guess we'll just live with it and become dinosaurs.
