### ISSUE TITLE
Issue in http index task

### ISSUE THREAD

**Issue by brunowego** [bezoerb/generator-grunt-symfony#15]
After run `http:index` I get this error:

``` bash
Running "http:index" (http) task
Fatal error: 500 Error: connect ECONNREFUSED<br> &nbsp; &nbsp;at exports._errnoException (util.js:746:11)<br> &nbsp; &nbsp;at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
```

Any idea? Thanks!

OSX 10.10

**Comment by brunowego** [comment]
This happens after the first run. I think the php service is open.

**Comment by bezoerb** [comment]
@brunowego just checked on OSX 10.10 and got the same error after running `grunt fetch`. I added a new alias to `grunt/aliases.js`

``` javascript
...
fetchtest: function(){
    grunt.connectMiddleware = getMiddleware();
    grunt.task.run(['connect:fetch:keepalive']);
},
```

I ran running `grunt fetchtest` and pointed chrome to `http://127.0.0.1:9000` and an osx dialog popped up asking me to allow/deny network the incoming connection.  
After allowing everything worked as expected.

**Comment by brunowego** [comment]
Thanks for try help me @bezoerb :+1: 

First I enable the firewall, after I allowed the connection, the issue continue with the same message.

**Comment by bezoerb** [comment]
hmpf... i think i'll give it another try tomorrow. 
Have you checked your symfony installation with some default apache virtualhost?

**Comment by brunowego** [comment]
Default installation, not changed anything.

**Comment by bezoerb** [comment]
which grunt task are you trying to run when the error occurs? you aren't running `grunt http` directly, right? Does `grunt serve` work for you?

**Comment by brunowego** [comment]
`grunt http` not works, but `grunt serve` works fine.

``` bash
grunt http

Running "http:index" (http) task
Fatal error: connect ECONNREFUSED
```

The problem is with the `build`.

``` bash
[...]
Running "autoprefixer:dist" (autoprefixer) task
>> 1 autoprefixed stylesheet created.

Running "fetch" task

Running "connect:fetch" (connect) task
Started connect web server on http://127.0.0.1:9000

Running "http:index" (http) task
Fatal error: 500 Error: connect ECONNREFUSED<br> &nbsp; &nbsp;at exports._errnoException (util.js:746:11)<br> &nbsp; &nbsp;at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
```

**Comment by bezoerb** [comment]
Have you tried changing the port?

**Comment by brunowego** [comment]
Same error after changing the port. I will test on other computers.

**Comment by bezoerb** [comment]
@brunowego any updates on this?

**Comment by brunowego** [comment]
It continues with the same error. However in other computer works. Maybe it's some error in my mec.
