### ISSUE TITLE
Usemin config

### ISSUE THREAD

**Issue by MichaelKubovic** [bezoerb/generator-grunt-symfony#16]
Symfony's asset() helper also accepts second parameter.

The following updated regular expression matches

``` regex
asset\(['"]([^'"]+(?:css|js|jpg|jpeg|gif|png|webp))['"](?:,[ ]?['"].+['"])?\)
```

matches the following pattern

``` twig
{{ asset('css/style.css', 'mad') }}
```

**Comment by bezoerb** [comment]
@MichaelKubovic awesome. thanks :)

**Comment by bezoerb** [comment]
i think i found a much more useable solution to handle renamed assets inside of Twig templates.
See #17
