### ISSUE TITLE
Bad assets path when site is not at the domain root and/or on windows

### ISSUE THREAD

**Issue by fredpeaks** [bezoerb/generator-grunt-symfony#18]
Hi, thanks for this amazing generator.

When I use this generator to create my site inside a folder which is not located at the root of my server domain, the assets are not loaded (css, js, and img) because the urls are not correct.
The problem comes from the FilerevPackage which doesn't use the "framework.templating.assets_base_urls" configuration to build absolute paths when needed.

Another problem I've found is that the assets urls are not correctly rewrote on windows by the FilerevPackage, because filerev.json contains windows style paths (with \ instead of /).
I've manage fix this by replacing this line (https://github.com/bezoerb/generator-grunt-symfony/blob/master/app/templates/symfony/Utils/GruntBundle/Templating/Asset/FilerevPackage.php#L143): 
`$reved = $this->summary->get($file);`
By this one:
`$reved = str_replace('\\', '/', $this->summary->get(str_replace('/', '\\', $file)));`

But I think the best solution would be to always write "url style" paths inside filerev.json, even on windows, because these are urls and not file paths.

Finally there is also a similar problem with the files included inside css (fonts, background images, ...).
The paths are not rewrote correctly to reflect the position of the website relatively to the domain.

**Comment by bezoerb** [comment]
@fredpeaks thanks for pointing this out. Currently i've no windows machine here to check the windows style paths issue but i'll take a look at the `framework.templating.assets_base_urls` config option in the next days.

**Comment by bezoerb** [comment]
@fredpeaks just updated `master` with a complete rewrite of the FilerevPackage. Could you try this one on windows?

**Comment by bezoerb** [comment]
https://github.com/bezoerb/generator-grunt-symfony/releases/tag/v0.5.2

**Comment by bezoerb** [comment]
Closed due lack of feedback.
Feel free to re-open if the issue still exists
