### ISSUE TITLE
yo error upon git initialization

### ISSUE THREAD

**Issue by MichaelKubovic** [bezoerb/generator-grunt-symfony#19]
I've tried to generate new project but the generator failed.. Choosing "No" for git repo seems to avoid the problem.

michael-mbp:sftest michael$ yo grunt-symfony

```
 _-----_
|       |    .-----------------------------------------.
|--(o)--|    | Welcome to the Grunt Symfony generator! |
```

   `---------´   '-----------------------------------------'
    ( _´U`_ )
    /**_A**_\
     |  ~  |
   **'._**.'__
 ´   `|° ´ Y`
## ? Would you like to use the Symfony "Standard Edition 2.6" distribution: Yes

? Would you like to include a CSS framework? No Framework
? Would you like to use a CSS preprocessor? Sass
? Would you like to use libsass? Read up more at
https://github.com/andrew/node-sass#node-sass: Yes
? Which module loader would you like to use? RequireJS
? Which additional plugins should i integrate for you? UnCSS - A grunt task for removing unused CSS, Critical - Extract & Inline Critical-path CSS
? Would you like to enable Git for this project? Yes
     info ... Fetching https://github.com/symfony/symfony-standard/archive/2.6.tar.gz ...
     info This might take a few moments
..✔ Done in /Users/michael/.cache/yeoman/symfony/symfony-standard/2.6
Initialized empty Git repository in /Users/michael/Sites/sftest/.git/
/Users/michael/.nvm/versions/v0.12.7/lib/node_modules/generator-grunt-symfony/app/index.js:843
                    this.fs.chmodSync(this.destinationPath('.git/hooks/post-me
                            ^
TypeError: undefined is not a function
    at null.<anonymous> (/Users/michael/.nvm/versions/v0.12.7/lib/node_modules/generator-grunt-symfony/app/index.js:843:29)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)

**Comment by bezoerb** [comment]
Thanks.
i'll take a look
