### ISSUE TITLE
PLANNED FEATURES

### ISSUE THREAD

**Issue by FossPrime** [bezoerb/generator-grunt-symfony#208]
- [ ] Gulp support (bezoerb)

---

OG:
There should be an issue, readme or wiki for plans... I've noticed some WebPack code and a BrowserSync overhaul?

**Comment by bezoerb** [comment]
Hey @rayfoss, 
thanks for the issue. What exactly are you missing?
I'm currently working on a rewrite which should also support gulp.
As for now you can already choose between requirejs, jspm, webpack and browserify for bundling and the implementations of those should already do the job.

**Comment by FossPrime** [comment]
@bezoerb Would you be open to also having Silex be an option (experimentally)? It seems that it could be a drop in replacement. A fork may be more appropriate if things get out of hand. I'm using it for a lightweight scalable backend. Performance is acceptable.

Also... docker support would be absolutely AWESOME. I've tried a few of the grunt plugins... they are really bad... perhaps I should use a general node package.

**Comment by FossPrime** [comment]
Silex Update:
Tried to install it as a Symfony distribution on the first Yeoman step... it worked! 

I only had to configure the router from [Google Bookshelf 2](https://github.com/GoogleCloudPlatform/getting-started-php), update the autoloader, install yaml, install google apiclient and move the test folder.

The result is it works with "grunt serve", browsersync, webpack... not 100% but close enough!

**Comment by FossPrime** [comment]
@bezoerb so how are you planning to go from grunt to gulp? it is becoming the case that the entire project looks outdated because of grunt. A rename should redirect traffic and keep the activity here... "generator-gulp-symfony" although if anyone is still fighting for Grunt, they would not be happy.

I'm excited to see how fast the dev server can run with gulp

**Comment by kuborgh-bzoerb** [comment]
@rayfoss wanna try https://github.com/bezoerb/generator-sf?

**Comment by bezoerb** [comment]
@rayfoss wanna try https://github.com/bezoerb/generator-sf? (now with the right user ;))
