### ISSUE TITLE
separate bundle

### ISSUE THREAD

**Issue by MichaelKubovic** [bezoerb/generator-grunt-symfony#21]
I'd love to see separate bundle handling rewrite based on json configuration. This has massive use-case across any front-end build environment revving files, be it any proprietary grunt setup (like mine), gulp, webpack, whatever....

Also, I'm thinking about moving applyVersion algorithm into separate version strategy implementing Symfony\Component\Asset\VersionStrategy\VersionStrategyInterface.

One more time thank you for a brilliant approach on revving front-end assets in sf2 - idea worth a blog post!

**Comment by bezoerb** [comment]
@MichaelKubovic i'm planing to move the bundle to packagist as soon as i have some time to work on this. Thanks for the thanks ;)

**Comment by bezoerb** [comment]
@MichaelKubovic Bundle separated. See https://github.com/bezoerb/FilerevBundle
