### ISSUE TITLE
404 on prod for assets

### ISSUE THREAD

**Issue by bcosynot** [bezoerb/generator-grunt-symfony#37]
I am not completely sure whats going on, but I am getting a 404 for the assets because the template is still using the unprocessed files.

I am using an apache2 server and ran `grunt build` before accessing the site on Ubuntu.

**Comment by bcosynot** [comment]
The above is also true when I just run `grunt serve:dist` on Windows and Ubuntu.

**Comment by bezoerb** [comment]
@vr3690 could you provide the configuration you used?

**Comment by bcosynot** [comment]
@bezoerb using browsersync, sass, requirejs, critical and bootstrap 

Is this what you needed or were you looking for some other information?

**Comment by bezoerb** [comment]
nope, this is what i was looking for. I'll see if i can reproduce the behavior.

**Comment by bcosynot** [comment]
Forgot to mention, I am using symfony 2.7

**Comment by bezoerb** [comment]
I think this is the cause for the issue ;)
See https://github.com/bezoerb/generator-grunt-symfony/pull/20

**Comment by bcosynot** [comment]
FYI, I tried the updates in commit dff7e1d3695cb8c0e23d8ffbd180ae8762abc2b1, but that did not help. Maybe I missed something.

**Comment by bezoerb** [comment]
@vr3690 i had no problems with symfony 2.7
just released a new version. wanna give it a try?

**Comment by bezoerb** [comment]
https://github.com/bezoerb/generator-grunt-symfony/releases/tag/v0.6.0

**Comment by bcosynot** [comment]
Yup. Seems to be working now. Thanks!

**Comment by bcosynot** [comment]
Also, just FYI, this works with the newly released 2.8 too.
